databases:
  - name: instant_web_video_edit
    databaseName: instant_web_video_edit
    user: instant_web_video_edit
    plan: free

services:
  - type: web
    name: instant_web_video_edit
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand は有料インスタンスのみ利用可能
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: instant_web_video_edit
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # メモリの過剰消費を避けるための推奨値

